# Generated by Django 3.0.3 on 2020-03-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200303_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
