# Generated by Django 3.0.3 on 2020-03-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
