# Generated by Django 3.0.3 on 2020-03-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200320_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
