# Generated by Django 3.0.3 on 2020-12-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background',
            field=models.CharField(choices=[('green', 'green'), ('pink', 'pink')], default='green', max_length=10),
            preserve_default=False,
        ),
    ]
