# Generated by Django 3.0.3 on 2020-12-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_event_background'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Backgroundimage',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
