# Generated by Django 3.0.3 on 2020-12-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201224_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='picture',
            field=models.ImageField(upload_to='background/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/event_image'),
        ),
    ]
