# Generated by Django 3.0.3 on 2020-12-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201227_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background',
            field=models.CharField(choices=[('../media/image/backgroundimage/green.jpg', 'green'), ('../media/image/backgroundimage/pink.jpg', 'pink')], max_length=40),
        ),
    ]
