# Generated by Django 3.0.3 on 2020-12-27 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('app', '0014_auto_20201227_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('handlename', models.CharField(max_length=15)),
                ('introduction', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/')),
            ],
        ),
    ]
